### ISSUE TITLE
Don't pollute the global namespace

### ISSUE THREAD

**Issue by nickforddev** [vladocar/femtoJS#1]
Currently this library pollutes the `window` object with global variables. A few suggestions:

- Wrap in an agnostic module wrapper to support commonjs, es6, and umd/amd modules.
- Attach the methods to the `$` instance instead of window, and return `$`

**Comment by vladocar** [comment]
You mean something like this: https://github.com/vladocar/nanoJS/blob/master/src/nanoJS.js ?

**Comment by daniellizik** [comment]
If you use rollup or something it'll do it for you automatically

**Comment by LoganDark** [comment]
@nickforddesign It no longer creates any global variables but `$`. All methods that return values now return values instead of doing weird things.

If you don't like `window.$` then tell me and I'll reopen the issue

**Comment by nickforddev** [comment]
It's definitely a step in the right direction, and i'm not against `window.$`.

I do think that ideally it's a module that returns `$` so you can do:

```js
const $ = require('femtojs');
```

As @daniellizik pointed out, adding a build tool like webpack (in `lib` mode) or rollup to this project would make that super easy.

**Comment by LoganDark** [comment]
The problem is that in a browser you can't return anything. Also, I just realized I fucked up a little bit and this won't work in node.js because there's no `window`. Let me fix that real quick

**Comment by LoganDark** [comment]
This library should support CommonJS, AMD, and regular `<script>` tags now as of the latest commit https://github.com/vladocar/femtoJS/commit/b92c4bca874119e05df5ed972f79e720f6772f43.

**Comment by vivekrc** [comment]
How do use this in a project via import and not polluting the global namespace?

**Comment by LoganDark** [comment]
@vivekrc See here:

https://github.com/vladocar/femtoJS/blob/3d8d4560ebb8d19bbfa458d595a5642fcd14dc6e/src/femtoJS.js#L103-L111

You definitely can import it like `import * as $ from 'femtojs'` or so
