### ISSUE TITLE
Don't mix es5 and es6

### ISSUE THREAD

**Issue by nickforddev** [vladocar/femtoJS#2]
If you're going to use es6 syntax, you should be using `const` instead of `var`.

I highly recommend you set up [eslint](https://eslint.org/) as well, with a common config like [standardjs](https://standardjs.com/) or [airbnb](https://www.npmjs.com/package/eslint-config-airbnb-base)

**Comment by LoganDark** [comment]
There are no `var`s anymore, and everything is properly scoped in an IIFE. The only global is now `$`.
