### ISSUE TITLE
what is `s`?

### ISSUE THREAD

**Issue by LoganDark** [vladocar/femtoJS#5]
I see a bunch of functions using the variable `s`, well I don't see it defined anywhere, what is `s`?? Does this mean every instance of the object shares the exact same state?

**Comment by Caitacular** [comment]
Exactly what you said. If you look at the definition of the `$()` function, you'll see it says:

`var $ = (selector) => {s = document.querySelectorAll(selector); return this}`

And since you chain each function, they all opperate on that returned object, all getting access to `s`.

**Comment by LoganDark** [comment]
So...

```js
$('body')

$.parent()

console.log(s)
```

returns the `html` element?

I don't mean to offend, but WTF?

**Comment by LoganDark** [comment]
And by "I don't see it defined", I mean exactly that. `s = ` in the `$` function is supposed to set it, it's not a declaration. Well, it's a declaration of a global variable, but I was really really hoping it wasn't. Apparently it is. Wow.

**Comment by LoganDark** [comment]
> they all opperate on that returned object, all getting access to s.

`this` doesn't even store anything, `s` is apparently a global variable. Shouldn't `$()` return an object with methods that operate on that object, rather than `$()` just changing some global state and then having all functions operate on the same state no matter where you are in the app? Shouldn't you be able to store this stuff for later like with jQuery objects? Ugh, so many questions, and sadly the answer's probably going to be "the library does this badly".

**Comment by Caitacular** [comment]
You're right, misread that, my bad. I misremembered scope with undeclared globals since it's a bad practice. 

I honestly think the author was practicing a code golf version of his nanojs library, and so this feels iffy cause it isn't meant to be robust. I hope that's right, cause otherwise, yeesh it's full of holes

**Comment by LoganDark** [comment]
Well, #7 should fix this issue and more, and should make the library a lot more useful.
